entertainment_arrivals:
    resource: "@EntertainmentArrivalsBundle/Controller/"
    type:     annotation
    prefix:   /

entertainment_red_carpet:
    resource: "@EntertainmentRedCarpetBundle/Controller/"
    type:     annotation
    prefix:   /

entertainment_guide_to_the_stars:
    resource: "@EntertainmentGuideToTheStarsBundle/Controller/"
    type:     annotation
    prefix:   /

#events_home:
#    path: /events/home
#    defaults: { _controller: EntertainmentGuideToTheStarsBundle:Events:hello }