entertainment_guide_to_the_stars:
    resource: "@EntertainmentGuideToTheStarsBundle/Controller/"
    type:     annotation
    prefix:   /

#events_home:
#    path: /events/home
#    defaults: { _controller: EntertainmentGuideToTheStarsBundle:Events:hello }